### ISSUE TITLE
available checkpoint

### ISSUE THREAD

**Issue by coding-sharks** [guxm2021/MM_ALT#3]
Could you provide the checkpoint file of wav2vec trained by DSinger? I am very interested in your research.

**Comment by guxm2021** [comment]
Thank you for your interests on our work. I think we have already provided the checkpoints for audio-only ALT system based on wav2vec 2.0 trained on the DSing dataset at: https://github.com/guxm2021/MM_ALT/tree/main/DSing/ALT. This format is in accord with SpeechBrain.

**Comment by coding-sharks** [comment]
My fault, I couldn't find it before. Thank you very much for the link.
